### PR TITLE
Added CXR and C-spine training code

### PR DESCRIPTION
**Pull request by blackboxradiology**

### CODE REVIEW

**Comment by anbhimi** [comment]
Please rectify the following issues -
1. Cell - 17 in race_detection_MIMIC_resnet34_2021_05_12.ipynb ran into an error.
2. Cell - 17 in race_detection_resnet34_2021_05_12.ipynb ran into a similar error.

**Comment by blackboxradiology** [comment]
> Please rectify the following issues -
> 
>     1. Cell - 17 in race_detection_MIMIC_resnet34_2021_05_12.ipynb ran into an error.
> 
>     2. Cell - 17 in race_detection_resnet34_2021_05_12.ipynb ran into a similar error.

Was this where model.fit is being called? was it an OOM error?

**Comment by anbhimi** [comment]
Both the errors occurred while fitting the model and they are not OOM errors. It seems they are KeyboardInterrupt errors.

**Comment by blackboxradiology** [comment]
> Both the errors occurred while fitting the model and they are not OOM errors. It seems they are KeyboardInterrupt errors.

I see what you mean.
Does `race_detection_CHEXPERT_resnet34_2021_05_29.ipynb` look correct though?
I'll fix these up with the new random seed. Thank you.

**Comment by anbhimi** [comment]
Yes, `race_detection_CHEXPERT_resnet34_2021_05_29.ipynb` file looks good. Thank You

**Pull request merged**
