### PR TITLE
MIMIC_Race_Classification

### PR DESCRIPTION
**Pull request by Ryan-RE-Wang**
Hi, my name is Ryan,  I am professor Po-Chih Kuo's student in National Tsing Hua University. The two notebook is for race classification with mimic dataset. Notebook named Race_classification_MIMIC_V2 contains the training and testing code for Densenet121 on mimic data, the testing part include classify race under different BMI groups, different age intervals, two genders, and also contain race classification result of blur, noisy, and msked CXRs. Another notebook is the training and testing code for "No Finding" label only CXRs. I also upload the csv file for height and weight for these patients, but for model and images data is too large to push through git. So I upload TFrecords for training and testing to google drive and here is the link  https://drive.google.com/drive/folders/1QM7edpPYwLDL4QZxyP4o606JSzs3Njj_?usp=sharing

### CODE REVIEW

**Comment by anbhimi** [comment]
@Ryan-RE-Wang,
Can you drop these two notebooks into a folder and name the folder accordingly? And also drop the CSV files into the folder as necessary (provided the data files do not contain any medical data).

**Comment by Ryan-RE-Wang** [comment]
Yes, I would put the new notebook into folder and resend pull request.
Thanks a lot.

Best regards,
Ryan Wang

Ananth Reddy ***@***.***> 於 2021年6月27日 週日 03:39 寫道：

**Comment by anbhimi** [comment]
@Ryan-RE-Wang,
Before resending the PR, please re-train the models with a random seed of 2021, if it is not performed.

**Comment by Ryan-RE-Wang** [comment]
Got it.

Ananth Reddy ***@***.***> 於 2021年6月28日 週一 下午9:38寫道：

**Comment by Ryan-RE-Wang** [comment]
Dnet121.zip
<https://drive.google.com/file/d/1Z2l8sMgLNjvwxFLwwIsH29LAddCoQDpO/view?usp=drive_web>
 Dnet121_No_finding.zip
<https://drive.google.com/file/d/1E0nTxSxhh7lRgudPNq1runmMJ9EX6bV0/view?usp=drive_web>
Hi, here are the models for the race classification project. The model
named as Dnet121 is for section A1 in supplemental material, the model
named as Dnet121_No_finding is for section B3.

ryan wang ***@***.***> 於 2021年6月29日 週二 下午1:13寫道：

**Pull request closed without merging**
